#!/usr/bin/env python3
"""Generate docs/ASSET_MANIFEST.md and data/manifest/asset_manifest.json
from the contents of Assets/.

This is a repository-owned audit tool (MVP 0). It never modifies the
original Assets/ tree; it only reads it and writes the two generated
outputs below. Re-run it whenever Assets/ changes so the manifest and the
in-engine validator (tools/validate_asset_manifest.gd) stay in sync.

Usage: python3 tools/generate_asset_manifest.py
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "Assets"
DOCS_MD = ROOT / "docs" / "ASSET_MANIFEST.md"
DATA_JSON = ROOT / "data" / "manifest" / "asset_manifest.json"

IMAGE_EXTS = {".png", ".jpg", ".jpeg"}

DIM_RE = re.compile(r"(\d+)\s*x\s*(\d+)", re.IGNORECASE)


def image_dimensions(path: Path):
    """Best-effort dimension probe using the system `file` command.

    Avoids a hard Pillow/ImageMagick dependency since this script only
    needs to run occasionally by a human or CI, not at game runtime.
    """
    try:
        out = subprocess.run(
            ["file", "--brief", str(path)],
            capture_output=True,
            text=True,
            check=False,
        ).stdout
    except FileNotFoundError:
        return None
    matches = DIM_RE.findall(out)
    if not matches:
        return None
    # JPEG `file` output can report a "density WxH" segment before the real
    # "precision 8, WxH, components" dimensions; the last match is correct
    # for both PNG (single match) and JPEG (last match) output.
    width, height = matches[-1]
    return int(width), int(height)


def classify(rel_parts):
    """Derive campaign/category/subject metadata from the path parts."""
    info = {"campaign": None, "category": None, "subject": None}
    if rel_parts[0] == "Campaign" and len(rel_parts) >= 2:
        info["campaign"] = rel_parts[1]
        if len(rel_parts) >= 3:
            info["category"] = rel_parts[2]
        if len(rel_parts) >= 4:
            info["subject"] = "/".join(rel_parts[3:-1]) or rel_parts[3]
    else:
        info["campaign"] = "(shared)"
        info["category"] = rel_parts[0]
        if len(rel_parts) >= 2:
            info["subject"] = "/".join(rel_parts[1:-1]) or None
    return info


def collect():
    entries = []
    for path in sorted(ASSETS_DIR.rglob("*")):
        if path.is_dir():
            continue
        if path.suffix == ".import":
            # Godot editor metadata sidecar, not an original asset.
            continue
        rel = path.relative_to(ASSETS_DIR)
        rel_parts = list(rel.parts)
        meta = classify(rel_parts)
        ext = path.suffix.lower()
        entry = {
            "path": "Assets/" + rel.as_posix(),
            "type": "image" if ext in IMAGE_EXTS else ("text" if ext == ".txt" else "other"),
            "extension": ext.lstrip("."),
            "campaign": meta["campaign"],
            "category": meta["category"],
            "subject": meta["subject"],
            "size_bytes": path.stat().st_size,
        }
        if entry["type"] == "image":
            dims = image_dimensions(path)
            if dims:
                entry["width"], entry["height"] = dims
        entries.append(entry)
    return entries


def write_json(entries):
    DATA_JSON.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated_by": "tools/generate_asset_manifest.py",
        "asset_count": len(entries),
        "assets": entries,
    }
    DATA_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_markdown(entries):
    by_campaign = {}
    for e in entries:
        by_campaign.setdefault(e["campaign"], []).append(e)

    lines = []
    lines.append("# Asset Manifest")
    lines.append("")
    lines.append(
        "Generated by `tools/generate_asset_manifest.py`. Do not edit by hand; "
        "re-run the script after Assets/ changes and commit both this file and "
        "`data/manifest/asset_manifest.json`."
    )
    lines.append("")
    lines.append(f"Total files under `Assets/`: **{len(entries)}**")
    lines.append("")
    lines.append("## Summary by campaign/group")
    lines.append("")
    lines.append("| Group | File count |")
    lines.append("|---|---|")
    for campaign in sorted(by_campaign):
        lines.append(f"| {campaign} | {len(by_campaign[campaign])} |")
    lines.append("")

    for campaign in sorted(by_campaign):
        lines.append(f"## {campaign}")
        lines.append("")
        lines.append("| Path | Type | Dimensions | Size |")
        lines.append("|---|---|---|---|")
        for e in sorted(by_campaign[campaign], key=lambda x: x["path"]):
            dims = f"{e['width']}x{e['height']}" if "width" in e else "-"
            size_kb = f"{e['size_bytes'] / 1024:.1f} KB"
            lines.append(f"| `{e['path']}` | {e['type']} | {dims} | {size_kb} |")
        lines.append("")

    DOCS_MD.parent.mkdir(parents=True, exist_ok=True)
    DOCS_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    entries = collect()
    write_json(entries)
    write_markdown(entries)
    print(f"Wrote {DATA_JSON.relative_to(ROOT)} ({len(entries)} entries)")
    print(f"Wrote {DOCS_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
